// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Home: typeof import('./components/Home.vue')['default']
    Lang: typeof import('./components/Lang.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    MessageApi: typeof import('./components/message-api.vue')['default']
    MockTest: typeof import('./components/mockTest.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    Pinia: typeof import('./components/Pinia.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  }
}

export {}
